### ISSUE TITLE
Missing line in  cfDNA/data/Ensembl_v75/README

### ISSUE THREAD

**Issue by janrehker** [shendurelab/cfDNA#2]
Hi,
It seems there is line 4 missing in the README file which leads to an absent file that is needed for consecutive processing.
My guess is that it would be something like:
./extractGeneBody.py | bgzip -c > ensemblv75_canonicalTranscriptIDs.protein_coding.lst.gz

Another issue:  cfDNA/WPS_overlays/Maurano_et_al_TFclusters/README seems to refer to data/Maurano_et_al_func_var/hg19.taipale.recluster.counts in line 18. How do I get this file?

Thanks,
Jan

**Comment by makirc** [comment]
I added the missing Encode file and added a line to DNA/WPS_overlays/Maurano_et_al_TFclusters/README for generating the count file. I hope this resolves your problems.
