### ISSUE TITLE
Unable to run plots.R

### ISSUE THREAD

**Issue by cviner** [shendurelab/cfDNA#3]
I am having some difficulties getting [```plots.R```](https://github.com/shendurelab/cfDNA/blob/master/expression/plots.R) to run upon the FFT summary data output by ```convert_files.py``` (everything up to this point worked as expected).

I am using the Protein Atlas file from: http://v13.proteinatlas.org/download/rna.csv.zip. (The link provided in the Human Protein Atlas section of the [README](https://github.com/shendurelab/cfDNA/blob/master/README.md) is no longer functioning.) It appears that the Protein Atlas file actually used was post-processed, to convert it from comma- to tab-delimited and likely also to rename some columns, based upon the ```plots.R``` script.

The main issue I am currently encountering has to do with the first computation of a correlation, on [line 36](https://github.com/shendurelab/cfDNA/blob/master/expression/plots.R#L36). The issue is that ```logndata2``` has all NAs, since its assignment on [line 34](https://github.com/shendurelab/cfDNA/blob/master/expression/plots.R#L34) does not work. This appears to be due to the initial assignment of row names (```rownames(proteinAtlas) <- proteinAtlas$GeneID```; [line 6](https://github.com/shendurelab/cfDNA/blob/master/expression/plots.R#L6)) not working, since there is no ```GeneID``` column in my Protein Atlas file.

However, if I change this assignment to instead use the ```Gene``` column, it does not work due to non-unique row names since there are multiple FPKM values per gene ID (one per tissue type or cell line).

If I instead re-write [line 34](https://github.com/shendurelab/cfDNA/blob/master/expression/plots.R#L34) as follows:

```R
    labelledLogndata <- cbind(proteinAtlas[,1], logndata)
    logndata2 <- labelledLogndata[labelledLogndata[,1] %in% fdata[,1],]
```

to not depend upon row names, I end up with a ```logndata2``` dimension of *Z* x 5, while ```fdata``` has a dimension of *Y* x 64, where the number of genes are equal, but *Z* and *Y* are not. The correlation on [line 36](https://github.com/shendurelab/cfDNA/blob/master/expression/plots.R#L36) currently uses ```logndata2``` directly, but this results in a non-numeric error. If I instead use ```logndata2[,3]```, to obtain the FPKM column, I then obtain an incompatible dimension error. Finally on line 39, ```logndata2[,"NB.4"]``` is used, but I do not have any columns with a ```NB.4``` label.

Is there another version of the script which pre-processed the data to resolve this or am I perhaps using an incorrect Protein Atlas file? If you have any suggestions on how to resolve these issues, please let me know.

**Comment by makirc** [comment]
Sorry for the trouble. I put the converted protein atlas data in data/protein_atlas, I hope this resolves the issue. Please let me know how this goes. Thanks!

**Comment by cviner** [comment]
Thank you! I am now able to create the first plot ("allFreq_correlation_plot.pdf").

After that I run into an error: ```object 'selFreq' not found```. The object ```selFreq```, first used on [line 55](https://github.com/shendurelab/cfDNA/blob/master/expression/plots.R#L55) does not appear to be defined.

**Comment by makirc** [comment]
Sorry cleaning up these things before putting them online obviously introduced typos, so the "freq" variable should be called "selFreq". I changed the script on GIT. Does it run through now?

**Comment by cviner** [comment]
Thanks!

It now stops on the next line ([56](https://github.com/shendurelab/cfDNA/blob/master/expression/plots.R#L56)) with: ```arguments imply differing number of rows: 0, 76```.

I am looking into the source of that error now.

**Comment by cviner** [comment]
Sorry, the above was my mistake. I had replaced the [```labels.txt```](https://github.com/shendurelab/cfDNA/blob/master/expression/labels.txt) file with the new [```tissue_key.tsv```](https://github.com/shendurelab/cfDNA/blob/master/data/protein_atlas/tissue_key.tsv) file.

**Comment by cviner** [comment]
The script now runs all the way through, producing the expected three PDF files.

I had to make one minor change: ```"P12.19.17_Normal"``` on [line 64](https://github.com/shendurelab/cfDNA/blob/master/expression/plots.R#L64) should be ```sample``` instead.

Thanks so much for all your help!
