### ISSUE TITLE
Canonical Transcript IDs selection

### ISSUE THREAD

**Issue by MuShuw** [shendurelab/cfDNA#5]
Hello,

I've been trying to get the same Canonical Transcript IDs that you uploaded in cfDNA/data/Ensembl_v75/

Though I don't come to the same list when using the above lists, to select the Canonical Transcript IDs. : 
- http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/knownCanonical.txt.gz
- http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/knownCanonical.txt.gz

Nor do I come to the same list when selecting the longest transcripts.

Would you mind telling me the way you settled for those particular transcripts ?
Did you use particular attributes obtained with BiomaRt to perform your selection ?

Best regards,
MushuW.

**Comment by makirc** [comment]
Dear MushuW,

Thank you for your message. We are not using files from UCSC here. As you suspect, we used BioMart to retrieve the list of canonical transcript IDs available in our repository. It seems no longer possible to that over the web, only the Perl and R API interfaces seem to provide access to that. Please have a look here for the response of Thomas Maurel on how to do it with the Perl API: http://gmod.827538.n3.nabble.com/biomart-users-How-to-download-all-human-canonical-transcript-IDs-from-Ensembl-version-75-via-BioMart-td4049474.html 

Best,

Martin

**Comment by MuShuw** [comment]
Dear Martin, 

Thank you for your answer. 
Your link to Thomas Maurel answer is very useful; new to Perl, I wasn't sure how to proceed.

Best of luck with your work,
MushuW.
